services:
    webapp:
      build: .
      ports:
        - "8000:8000"
      command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    app:
      build: .
      ports:
        - "8000:8000"
    unittests:
      build: .
      command: pytest
      volumes:
        - .:/app
      depends_on:
        - webapp